package menupresentation;

import helper.BackGroundPane;

import java.awt.Color;
import java.util.List;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

import entities.xml.Game;
import entities.xml.Level;
import entities.xml.User;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Andre
 */
public class TrackList extends javax.swing.JFrame {

	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel lblBestzeit;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextPane jTextPane1;
	private javax.swing.JTree jTree1;
	private JComboBox comboBox = new JComboBox();

	private JFrame parent;
	private User user;
	private List<Level> levels;
	private int[] roadMap;
	private int[][] landscapeMaps = {
			{ 2,3,3,3 },
			{ 0,1,1,1},
			{ 4,5,5,5 } };
	private int[] landscapeMap;
	private Color[][] gamesColors = {
			{ Color.BLUE, Color.ORANGE, Color.ORANGE, Color.RED, Color.WHITE,
					Color.WHITE },
			{ new Color( 25, 25, 112 ), new Color(112,128,144), Color.DARK_GRAY, Color.RED, Color.WHITE,
					Color.WHITE },
			{ Color.BLUE, Color.WHITE, Color.GRAY, Color.DARK_GRAY, Color.LIGHT_GRAY,
					Color.WHITE } };
	private Color[] gameColors;
	private Game game;
	/**
	 * Creates new form MainMenu
	 */
	public TrackList(javax.swing.JFrame parent, User user, Game game) {
		initComponents();
		this.user = user;
		this.game = game;
		this.parent = parent;
		this.levels = game.getLevels();
		myInitComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	private void initComponents() {

		jScrollPane2 = new javax.swing.JScrollPane();
		jTree1 = new javax.swing.JTree();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jPanel1 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextPane1 = new javax.swing.JTextPane();
		jLabel2 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		lblBestzeit = new JLabel();

		jPanel1.setOpaque(false);
		
		jScrollPane2.setViewportView(jTree1);

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("SEPGarbageRace");
		setBounds(new java.awt.Rectangle(100, 50, 800, 600));
		setResizable(false);
		setContentPane(new BackGroundPane("images/Hintergrund/Hintergrund3.png"));

//		jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36));
//		jLabel1.setText("SEPGarbageRace");

		jButton1 = setButtonStyle(jButton1, "Zurück", true);
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTextPane1.setEditable(false);
		jScrollPane1.setViewportView(jTextPane1);

		
		comboBox.setFont(new java.awt.Font("Kristen ITC", 0, 13));
		comboBox.setModel(new DefaultComboBoxModel(new String[] {
				"Ghost-Modus", "Standard-Modus" }));

		JLabel lblNewJgoodiesLabel = new JLabel();
		lblNewJgoodiesLabel.setFont(new java.awt.Font("Kristen ITC", 0, 17));
		lblNewJgoodiesLabel.setText("Spielmodus:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(44)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addComponent(
																lblBestzeit)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								Alignment.LEADING,
																								false)
																						.addComponent(
																								jScrollPane1,
																								GroupLayout.PREFERRED_SIZE,
																								313,
																								GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel1Layout
																										.createSequentialGroup()
																										.addComponent(
																												lblNewJgoodiesLabel)
																										.addPreferredGap(
																												ComponentPlacement.RELATED,
																												GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												comboBox,
																												GroupLayout.PREFERRED_SIZE,
																												141,
																												GroupLayout.PREFERRED_SIZE)))
																		.addGap(45)
																		.addComponent(
																				jButton4,
																				GroupLayout.PREFERRED_SIZE,
																				346,
																				GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(43, Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(49)
																		.addComponent(
																				jButton4,
																				GroupLayout.PREFERRED_SIZE,
																				309,
																				GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(57)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								Alignment.BASELINE)
																						.addComponent(
																								comboBox,
																								GroupLayout.PREFERRED_SIZE,
																								GroupLayout.DEFAULT_SIZE,
																								GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblNewJgoodiesLabel))
																		.addGap(18)
																		.addComponent(
																				jScrollPane1,
																				GroupLayout.PREFERRED_SIZE,
																				262,
																				GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												ComponentPlacement.RELATED)
										.addComponent(lblBestzeit)
										.addContainerGap(14, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		jLabel2.setFont(new java.awt.Font("Kristen ITC", 0, 17));
		lblBestzeit.setFont(new java.awt.Font("Kristen ITC", 0, 17));
		lblBestzeit.setForeground(new Color(255,76,0));

		jButton2 = setButtonStyle(jButton2, "Vor", true);
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3 = setButtonStyle(jButton3, "Zurück", true);
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton5 = setButtonStyle(jButton5, "Starten", true);
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jButton5,
																		GroupLayout.PREFERRED_SIZE,
																		117,
																		GroupLayout.PREFERRED_SIZE)
																.addGap(18)
																.addComponent(
																		jButton1,
																		GroupLayout.PREFERRED_SIZE,
																		117,
																		GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jPanel1,
																		GroupLayout.DEFAULT_SIZE,
																		GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(246)
																.addGroup(
																		layout.createParallelGroup(
																				Alignment.TRAILING,
																				false)
																				.addComponent(
																						jLabel1)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jButton3)
																								.addPreferredGap(
																										ComponentPlacement.RELATED,
																										GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE)
																								.addComponent(
																										jLabel2,
																										GroupLayout.PREFERRED_SIZE,
																										169,
																										GroupLayout.PREFERRED_SIZE)
																								.addPreferredGap(
																										ComponentPlacement.RELATED)
																								.addComponent(
																										jButton2)))
																.addGap(0,
																		274,
																		Short.MAX_VALUE)))
								.addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(37)
								.addComponent(jLabel1,
										GroupLayout.PREFERRED_SIZE, 45,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														jLabel2,
														GroupLayout.PREFERRED_SIZE,
														25,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(jButton2)
												.addComponent(jButton3))
//								.addGap(18)
								.addComponent(jPanel1,
										GroupLayout.PREFERRED_SIZE,
										GroupLayout.DEFAULT_SIZE,
										GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(ComponentPlacement.RELATED,
										30, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												Alignment.BASELINE)
												.addComponent(
														jButton1,
														GroupLayout.PREFERRED_SIZE,
														33,
														GroupLayout.PREFERRED_SIZE)
												.addComponent(
														jButton5,
														GroupLayout.PREFERRED_SIZE,
														33,
														GroupLayout.PREFERRED_SIZE))
								.addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}

	//Hier wird die erste Strecke geladen
    private void myInitComponents(){
        if(levels!=null && levels.size()>0){
        	fillFields(0);
        }
    }       
    
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		parent.setVisible(true);
		setVisible(false);
		dispose();
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		//Hier wird die naechste Strecke geladen
        if(levels!=null && levels.size()>0){
        	//Über die Level iterieren, bis die aktuelle Strecke gefunden wurde
        	for(int j=0; j<levels.size(); j++){
            	//Strecke gefunden
        		if(levels.get(j).getName().equals(jLabel2.getText())){
            		//Hier wird geprüft, ob die letzte Strecke ausgewählt ist
        			if((j+1)<levels.size()){
            			//Wenn nicht die letzte ausgewählt ist, dann wird die nächste Strecke angezeigt
        				fillFields(j+1);
                        break;
                   }
                   else{
                	   //Wenn die letzte Strecke ausgewählt ist, dann wird die erste Strecke angezeigt
                	   fillFields(0);
                       break;
                   }
               } 
            }
        }
	}
	
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		//Hier wird die vorherige Strecke geladen
		if(levels!=null && levels.size()>0){
        	//Über die Level iterieren, bis die aktuelle Strecke gefunden wurde
            for(int j=0; j<levels.size(); j++){
            	//Strecke gefunden
            	if(levels.get(j).getName().equals(jLabel2.getText())){
            		//Hier wird geprüft, ob die erste Strecke ausgewählt ist
            		if((j-1)>=0){
            			//Wenn nicht die erste ausgewählt ist, dann wird die vorherige Strecke angezeigt
            			fillFields(j-1);
            			break;
                   }
                   else{
                	   	//Wenn die erste Strecke ausgewählt ist, dann wird die letzte Strecke angezeigt
                	   	fillFields(levels.size()-1);
                	   	break;
                   }
               } 
            }
        }
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		setVisible(false);
		GameScreen gameScreen = new GameScreen(this, user, game,
				roadMap, landscapeMap, gameColors, jLabel2.getText(), comboBox.getSelectedItem().equals("Ghost-Modus"));
		gameScreen.setVisible(true);
		dispose();
	}
	
	private void fillFields(int index){
		
    	//Überschrift setzen
        jLabel2.setText(levels.get(index).getName());
        jLabel2.setHorizontalAlignment( SwingConstants.CENTER );
        //Bestzeit setzen
		lblBestzeit.setText("Bestzeit: "+levels.get(index).getHighscore().getEntries().get(0).getTime()+" - "+levels.get(index).getHighscore().getEntries().get(0).getUsername());
		lblBestzeit.setBackground(new Color(25,7,0));
		lblBestzeit.setOpaque(true);
		//Streckenbild laden
        jButton4.setIcon(new ImageIcon(levels.get(index).getModel()));
        
        gameColors = new Color[6];
		for (int i = 0; i < gameColors.length; i++) {
			gameColors[i] = gamesColors[index][i];
		}
		landscapeMap = new int[landscapeMaps[index].length];
		for (int i = 0; i < landscapeMap.length; i++) {
			landscapeMap[i] = landscapeMaps[index][i];
		}
		
		int roadMapLength = 1;
		for(char c:levels.get(index).getDirection().toCharArray()){
			if(c==',')
				roadMapLength++;
		}
		roadMap = new int[roadMapLength];
		
		int count = 0, start = 0;
		char[] ch = levels.get(index).getDirection().toCharArray();
		for(int i=0; i<ch.length;i++){
			if(ch[i]==','){
				roadMap[count] = Integer.valueOf(levels.get(index).getDirection().substring(start,i));
				count++;
				start = i+2;
			}
		}
		  //Beschreibung setzen
        jTextPane1.setText(levels.get(index).getDescription() + "\n\n" + "Hinternisse:" +(count/12) +"\n\n" + "Müll:" + (count/15) + "\n\n" + "Streckenart: " + levels.get(index).getSurface());
		roadMap[count] = Integer.valueOf(levels.get(index).getDirection().substring(start,levels.get(index).getDirection().length()));
    }
	
	//Hier wird der ButtonStyle gesetzt
    private JButton setButtonStyle(JButton b, String text, boolean enabled){
    	b.setFont(new java.awt.Font("Kristen ITC", 0, 17));
        b.setForeground(new Color(255,76,0));
        b.setText(text);
        b.setBackground(new Color(25,7,0));
        b.setEnabled(enabled);
        return b;
    }
}